export const CREATE_CONTENT = 'CREATE_CONTENT';
export const CREATE_CONTENT_FAIL = 'CREATE_CONTENT_FAIL';

export const GET_CONTENT = 'GET_CONTENT';
export const GET_CONTENT_FAIL = 'GET_CONTENT_FAIL';

export const DELETE_CONTENT = 'DELETE_CONTENT';
export const DELETE_CONTENT_FAIL = 'DELETE_CONTENT_FAIL';

export const GET_CONTENT_DETAILS = 'GET_CONTENT_DETAILS';
export const GET_CONTENT_DETAILS_FAIL = 'GET_CONTENT_DETAILS_FAIL';

export const ADD_FORM_FILE = 'ADD_FORM_FILE';
export const ADD_FORM_FILE_FAIL = 'ADD_FORM_FILE_FAIL';

export const GET_FORM_FILE = 'GET_FORM_FILE';
export const GET_FORM_FILE_FAIL = 'GET_FORM_FILE_FAIL';

export const DELETE_FORM_FILE = 'DELETE_FORM_FILE';
export const DELETE_FORM_FILE_FAIL = 'DELETE_FORM_FILE_FAIL';

export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const CREATE_CAMPAIGN_FAIL = 'CREATE_CAMPAIGN_FAIL';

export const GET_CAMPAIGN = 'GET_CAMPAIGN';
export const GET_CAMPAIGN_FAIL = 'GET_CAMPAIGN_FAIL';

export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const DELETE_CAMPAIGN_FAIL = 'DELETE_CAMPAIGN_FAIL';

export const GET_CAMPAIGN_DETAILS = 'GET_CAMPAIGN_DETAILS';
export const GET_CAMPAIGN_DETAILS_FAIL = 'GET_CAMPAIGN_DETAILS_FAIL';

export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_FAIL = 'CREATE_LIST_FAIL';

export const GET_LIST = 'GET_LIST';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';

export const DELETE_LIST = 'DELETE_LIST';
export const DELETE_LIST_FAIL = 'DELETE_LIST_FAIL';
